<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $uuid
     *
     * @return User|null    Null, if the uuid could not be found.
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByUuid($uuid)
    {
        $query = $this->createQueryBuilder('u')
            ->where('u.uuid = :uuid')
            ->setParameter('uuid', (string) $uuid)  // Sanitation is done here, too!
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
